@startuml
class ServiceCollectionExtensions <<static>> {
    + {static} AddConfiguration(serviceCollection:IServiceCollection) : IServiceCollection
    + {static} RegisterServices(serviceCollection:IServiceCollection) : IServiceCollection
}
@enduml
