@startuml
class PartyFileRepository {
    + PartyFileRepository(fileAccessor:IFileAccessor, options:IOptions<FileRepositoryOptions>)
    + Get() : Party
    + Save(party:Party) : void
}
IPartyRepository <|-- PartyFileRepository
@enduml
