//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DnDProbabilityCalculator.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DnDProbabilityCalculator.Core.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ability Score Value must be between 1 and 30.
        /// </summary>
        public static string Ability_Score_Out_Of_Range {
            get {
                return ResourceManager.GetString("Ability_Score_Out_Of_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An actor can only have one Attack Ability.
        /// </summary>
        public static string More_Than_One_Attack_Ability {
            get {
                return ResourceManager.GetString("More_Than_One_Attack_Ability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of attacks must be higher than zero.
        /// </summary>
        public static string Negative_Number_Of_Attacks {
            get {
                return ResourceManager.GetString("Negative_Number_Of_Attacks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided File cannot be deserialized into a Character Collection.
        /// </summary>
        public static string Wrong_File_Format {
            get {
                return ResourceManager.GetString("Wrong_File_Format", resourceCulture);
            }
        }
    }
}
